version: '3'
services:
  db:
    image: postgres
    volumes:
      - graphdb:/var/lib/postgresql/data
      - bundle:/usr/local/bundle
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  graphdb:
  bundle:
